apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbtest-deployment
spec:
  selector:
    matchLabels:
      app: mongodbtest
  template:
    metadata:
      labels:
        app: mongodbtest
    spec:
      containers:
      - name: mongodbtest
        image: mongo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
---
kind: Service
apiVersion: v1
metadata:
  name:  springmongodb
spec:
  selector:
    app:  mongodbtest
  type:  NodePort
  ports:
  - name:  mongodb
    port:  27017
    targetPort:  27017