apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom-deployment
spec:
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
      - name: nginx-custom
        image: ghodkenikhil/nginx-custom:1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name:  nginx-cus-service
spec:
  selector:
    app:  nginx-custom
  type:  NodePort
  ports:
  - name:  nginx-custom
    port:  80
    targetPort:  80